<?php

namespace AppBundle\Repository;

/**
 * FioulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FioulRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFioulbyIdBetweenTwoDate($id, \DateTime $fdate, \DateTime $sdate)
    {
        $query = $this->createQueryBuilder('f')
            ->select('f.amount')
            ->where('f.postalCodeId = :id')
            ->andwhere('f.date BETWEEN :first AND :second')
            ->setParameter('first', $fdate->format('Y-m-d'))
            ->setParameter('second', $sdate->format('Y-m-d'))
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
        return $query;
    }
}
